//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QPharma.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QPharma.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại.
        /// </summary>
        internal static string Account_does_not_exist {
            get {
                return ResourceManager.GetString("Account does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không hợp lệ. Vui lòng liên hệ quản lý !.
        /// </summary>
        internal static string Account_not_valid {
            get {
                return ResourceManager.GetString("Account not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Thêm &gt;&gt;.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm danh mục thành công.
        /// </summary>
        internal static string Add_category_successfully {
            get {
                return ResourceManager.GetString("Add category successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thất bại.
        /// </summary>
        internal static string Add_failed {
            get {
                return ResourceManager.GetString("Add failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thất bại.
        /// </summary>
        internal static string Add_failled {
            get {
                return ResourceManager.GetString("Add failled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vị trí thuốc thành công.
        /// </summary>
        internal static string Add_medicine_location_successfully {
            get {
                return ResourceManager.GetString("Add medicine location successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhà cung cấp thành công.
        /// </summary>
        internal static string Add_supplier_successfully {
            get {
                return ResourceManager.GetString("Add supplier successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thông tin thuốc thành công.
        /// </summary>
        internal static string Added_medicine_information_successfully {
            get {
                return ResourceManager.GetString("Added medicine information successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon appicon {
            get {
                object obj = ResourceManager.GetObject("appicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xoá vị trí thuốc này vĩnh viễn? Không thể khôi phục sau khi xoá.
        /// </summary>
        internal static string Are_you_sure_want_to_delete_this_medicine_location_ {
            get {
                return ResourceManager.GetString("Are you sure want to delete this medicine location?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xoá nhà cung cấp này vĩnh viễn? Không thể khôi phục sau khi xoá.
        /// </summary>
        internal static string Are_you_sure_want_to_delete_this_supplier_ {
            get {
                return ResourceManager.GetString("Are you sure want to delete this supplier?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa vĩnh viễn thể loại này?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_permanently_delete_this_category_ {
            get {
                return ResourceManager.GetString("Are you sure you want to permanently delete this category?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa vĩnh viễn thuốc này?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_permanently_remove_this_medication_ {
            get {
                return ResourceManager.GetString("Are you sure you want to permanently remove this medication?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xoá nhà cung cấp này không?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_remove_this_supplier_ {
            get {
                return ResourceManager.GetString("Are you sure you want to remove this supplier?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khả dụng.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chờ.
        /// </summary>
        internal static string Awaiting_payment {
            get {
                return ResourceManager.GetString("Awaiting payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bill__1_ {
            get {
                object obj = ResourceManager.GetObject("bill (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnDanhMuc_Image {
            get {
                object obj = ResourceManager.GetObject("btnDanhMuc_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNcc_Image {
            get {
                object obj = ResourceManager.GetObject("btnNcc_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnNhanVien_Image {
            get {
                object obj = ResourceManager.GetObject("btnNhanVien_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnQlyThuoc_Image {
            get {
                object obj = ResourceManager.GetObject("btnQlyThuoc_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnTaiChinh_Image {
            get {
                object obj = ResourceManager.GetObject("btnTaiChinh_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnThongTin_Image {
            get {
                object obj = ResourceManager.GetObject("btnThongTin_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi thêm thuốc.
        /// </summary>
        internal static string Cannot_added_this_medicine {
            get {
                return ResourceManager.GetString("Cannot added this medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa nhà cung cấp này.
        /// </summary>
        internal static string Cannot_edit_this_supplier {
            get {
                return ResourceManager.GetString("Cannot edit this supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sự cố khi lưu ảnh.
        /// </summary>
        internal static string Cannot_save_this_image {
            get {
                return ResourceManager.GetString("Cannot save this image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thể loại không tồn tại.
        /// </summary>
        internal static string Category_ID_does_not_exist {
            get {
                return ResourceManager.GetString("Category ID does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thể loại không hợp lệ.
        /// </summary>
        internal static string Category_ID_does_not_valid {
            get {
                return ResourceManager.GetString("Category ID does not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ DANH MỤC THUỐC.
        /// </summary>
        internal static string Category_management {
            get {
                return ResourceManager.GetString("Category management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thể loại đã tồn tại.
        /// </summary>
        internal static string Category_name_already_exists {
            get {
                return ResourceManager.GetString("Category name already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thể loại đã tồn tại trong mục lưu trữ.
        /// </summary>
        internal static string Category_name_already_exists_in_archive {
            get {
                return ResourceManager.GetString("Category name already exists in archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi ảnh thành công.
        /// </summary>
        internal static string Change_image_successfully {
            get {
                return ResourceManager.GetString("Change image successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thất bại.
        /// </summary>
        internal static string Change_password_fail {
            get {
                return ResourceManager.GetString("Change password fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công.
        /// </summary>
        internal static string Change_password_success {
            get {
                return ResourceManager.GetString("Change password success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớp.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNTT K19P.
        /// </summary>
        internal static string ClassValue {
            get {
                return ResourceManager.GetString("ClassValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close__1_ {
            get {
                object obj = ResourceManager.GetObject("close (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename={0};Integrated Security=True;Connect Timeout=30.
        /// </summary>
        internal static string ConnectString {
            get {
                return ResourceManager.GetString("ConnectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối đến cơ sở dữ liệu.
        /// </summary>
        internal static string Database_connection_error {
            get {
                return ResourceManager.GetString("Database connection error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, ngày {1} tháng {2} năm {3}.
        /// </summary>
        internal static string Date_format {
            get {
                return ResourceManager.GetString("Date format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thất bại.
        /// </summary>
        internal static string Delete_failed {
            get {
                return ResourceManager.GetString("Delete failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá thành công Mã thuốc {0}.
        /// </summary>
        internal static string Delete_medicine_id_successfully {
            get {
                return ResourceManager.GetString("Delete medicine id successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập chức năng này.
        /// </summary>
        internal static string Do_not_have_permission_to_access {
            get {
                return ResourceManager.GetString("Do not have permission to access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa ảnh này?.
        /// </summary>
        internal static string Do_you_want_to_delete_this_image {
            get {
                return ResourceManager.GetString("Do you want to delete this image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa danh mục thành công.
        /// </summary>
        internal static string Edit_Category_Successfully {
            get {
                return ResourceManager.GetString("Edit Category Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thất bại.
        /// </summary>
        internal static string Edit_failed {
            get {
                return ResourceManager.GetString("Edit failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa vị trí thuốc thành công.
        /// </summary>
        internal static string Edit_medicine_location_successfully {
            get {
                return ResourceManager.GetString("Edit medicine location successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin nhà cung cấp thành công.
        /// </summary>
        internal static string Edit_supplier_sucessfully {
            get {
                return ResourceManager.GetString("Edit supplier sucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn thoát?.
        /// </summary>
        internal static string Exit_confirm {
            get {
                return ResourceManager.GetString("Exit confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn sử dụng phải lớn hơn hoặc bằng Ngày sản xuất.
        /// </summary>
        internal static string Expiry_date_must_be_greater_than_or_equal_to_Production_date {
            get {
                return ResourceManager.GetString("Expiry date must be greater than or equal to Production date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floppy_disk {
            get {
                object obj = ResourceManager.GetObject("floppy-disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ sáu.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào, {0}.
        /// </summary>
        internal static string Hello_text {
            get {
                return ResourceManager.GetString("Hello text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_export_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-export-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_plus_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-plus-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_plus_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-plus-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_shutdown_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-shutdown-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_shutdown_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-shutdown-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ictuLogo {
            get {
                object obj = ResourceManager.GetObject("ictuLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        internal static string Invalid_email {
            get {
                return ResourceManager.GetString("Invalid email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thuốc không hợp lệ.
        /// </summary>
        internal static string Invalid_Medicine_ID {
            get {
                return ResourceManager.GetString("Invalid Medicine ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        internal static string Invalid_phone_number {
            get {
                return ResourceManager.GetString("Invalid phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảng viên.
        /// </summary>
        internal static string Lecturer {
            get {
                return ResourceManager.GetString("Lecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cô Nguyễn Lan Oanh.
        /// </summary>
        internal static string LecturerValue {
            get {
                return ResourceManager.GetString("LecturerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vị tri đã tồn tại.
        /// </summary>
        internal static string Location_name_already_exists {
            get {
                return ResourceManager.GetString("Location name already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vị tri đã tồn tại trong mục lưu trữ.
        /// </summary>
        internal static string Location_name_already_exists_in_archive {
            get {
                return ResourceManager.GetString("Location name already exists in archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại. Vui lòng liên hệ quản lý !.
        /// </summary>
        internal static string Login_fail {
            get {
                return ResourceManager.GetString("Login fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LoginBackgroundImage {
            get {
                object obj = ResourceManager.GetObject("LoginBackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn đăng xuất?.
        /// </summary>
        internal static string Logout_confirm {
            get {
                return ResourceManager.GetString("Logout confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainBackgroundImage {
            get {
                object obj = ResourceManager.GetObject("MainBackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thuốc đã tồn tại.
        /// </summary>
        internal static string Medicine_ID_already_exist {
            get {
                return ResourceManager.GetString("Medicine ID already exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thuốc đã tồn tại trong mục lưu trữ.
        /// </summary>
        internal static string Medicine_ID_already_exist_in_archive {
            get {
                return ResourceManager.GetString("Medicine ID already exist in archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thuốc không tồn tại.
        /// </summary>
        internal static string Medicine_ID_is_not_exist {
            get {
                return ResourceManager.GetString("Medicine ID is not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ VỊ TRÍ THUỐC.
        /// </summary>
        internal static string Medicine_location_management {
            get {
                return ResourceManager.GetString("Medicine location management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ THUỐC.
        /// </summary>
        internal static string Medicine_management {
            get {
                return ResourceManager.GetString("Medicine management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành viên.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyễn Mạnh Cường;
        ///Dương Hữu Hoàng;Nguyễn Hoàng Long;Phạm Văn Quyết.
        /// </summary>
        internal static string MembersValue {
            get {
                return ResourceManager.GetString("MembersValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ hai.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được quá {0} ký tự.
        /// </summary>
        internal static string Name_cannot_exceed_value {
            get {
                return ResourceManager.GetString("Name cannot exceed value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới không khớp.
        /// </summary>
        internal static string New_password_is_not_correct {
            get {
                return ResourceManager.GetString("New password is not correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không chính xác.
        /// </summary>
        internal static string Old_password_is_not_correct {
            get {
                return ResourceManager.GetString("Old password is not correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thanh toán.
        /// </summary>
        internal static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng tích chọn hoá đơn để xoá.
        /// </summary>
        internal static string Please_check_bill_to_delete {
            get {
                return ResourceManager.GetString("Please check bill to delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn vị trí thuốc.
        /// </summary>
        internal static string Please_choose_a_medicine_location {
            get {
                return ResourceManager.GetString("Please choose a medicine location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đầy đủ thông tin.
        /// </summary>
        internal static string Please_enter_complete_info {
            get {
                return ResourceManager.GetString("Please enter complete info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập lại mật khẩu mới.
        /// </summary>
        internal static string Please_enter_confirm_password {
            get {
                return ResourceManager.GetString("Please enter confirm password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu mới.
        /// </summary>
        internal static string Please_enter_new_password {
            get {
                return ResourceManager.GetString("Please enter new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu cũ.
        /// </summary>
        internal static string Please_enter_old_password {
            get {
                return ResourceManager.GetString("Please enter old password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên thể loại.
        /// </summary>
        internal static string Please_input_category_name {
            get {
                return ResourceManager.GetString("Please input category name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên vị trí.
        /// </summary>
        internal static string Please_input_location_name {
            get {
                return ResourceManager.GetString("Please input location name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã thuốc.
        /// </summary>
        internal static string Please_input_medicine_id {
            get {
                return ResourceManager.GetString("Please input medicine id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên thuốc.
        /// </summary>
        internal static string Please_input_medicine_name {
            get {
                return ResourceManager.GetString("Please input medicine name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập giá bán.
        /// </summary>
        internal static string Please_input_medicine_price_out {
            get {
                return ResourceManager.GetString("Please input medicine price_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số lượng.
        /// </summary>
        internal static string Please_input_medicine_quantity {
            get {
                return ResourceManager.GetString("Please input medicine quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đơn vị thuốc.
        /// </summary>
        internal static string Please_input_medicine_unit {
            get {
                return ResourceManager.GetString("Please input medicine unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã nhà cung cấp.
        /// </summary>
        internal static string Please_input_supplier_ID {
            get {
                return ResourceManager.GetString("Please input supplier ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên nhà cung cấp.
        /// </summary>
        internal static string Please_input_supplier_name {
            get {
                return ResourceManager.GetString("Please input supplier name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên của bạn.
        /// </summary>
        internal static string Please_input_your_name {
            get {
                return ResourceManager.GetString("Please input your name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thể loại.
        /// </summary>
        internal static string Please_select_a_category {
            get {
                return ResourceManager.GetString("Please select a category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn nhà cung cấp.
        /// </summary>
        internal static string Please_select_a_supplier {
            get {
                return ResourceManager.GetString("Please select a supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thuốc hợp lệ.
        /// </summary>
        internal static string Please_select_a_valid_medicine {
            get {
                return ResourceManager.GetString("Please select a valid medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thể loại muốn sửa.
        /// </summary>
        internal static string Please_select_the_category_you_want_to_edit {
            get {
                return ResourceManager.GetString("Please select the category you want to edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn nhà cung cấp muốn xoá !.
        /// </summary>
        internal static string Please_select_the_supplier_you_want_to_delete_ {
            get {
                return ResourceManager.GetString("Please select the supplier you want to delete!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn nhà cung cấp muốn chỉnh sửa.
        /// </summary>
        internal static string Please_select_the_supplier_you_want_to_edit {
            get {
                return ResourceManager.GetString("Please select the supplier you want to edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kê đơn.
        /// </summary>
        internal static string Prescription_drug {
            get {
                return ResourceManager.GetString("Prescription drug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá phải là số.
        /// </summary>
        internal static string Price_must_be_a_number {
            get {
                return ResourceManager.GetString("Price must be a number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá phải lớn hơn hoặc bằng 0.
        /// </summary>
        internal static string Price_must_be_greater_or_equal_0 {
            get {
                return ResourceManager.GetString("Price must be greater or equal 0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer__1_ {
            get {
                object obj = ResourceManager.GetObject("printer (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phải là số.
        /// </summary>
        internal static string Quantity_must_be_a_number {
            get {
                return ResourceManager.GetString("Quantity must be a number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phải lớn hơn hoặc bằng 0.
        /// </summary>
        internal static string Quantity_must_be_greater_or_equal_0 {
            get {
                return ResourceManager.GetString("Quantity must be greater or equal 0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khôi phục tất cả thuốc thành công.
        /// </summary>
        internal static string Restore_all_medicines_successfully {
            get {
                return ResourceManager.GetString("Restore all medicines successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khôi phục thất bại.
        /// </summary>
        internal static string Restore_failed {
            get {
                return ResourceManager.GetString("Restore failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã khôi phục Mã thuốc {0}.
        /// </summary>
        internal static string Restore_medicine_id_successfully {
            get {
                return ResourceManager.GetString("Restore medicine id successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_arrow {
            get {
                object obj = ResourceManager.GetObject("right-arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_arrow__1_ {
            get {
                object obj = ResourceManager.GetObject("right-arrow (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_arrow__2_ {
            get {
                object obj = ResourceManager.GetObject("right-arrow (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_arrow1 {
            get {
                object obj = ResourceManager.GetObject("right-arrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ bảy.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashScreen {
            get {
                object obj = ResourceManager.GetObject("SplashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn học.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ứng dụng công nghệ phát triển phần mềm.
        /// </summary>
        internal static string SubjectValue {
            get {
                return ResourceManager.GetString("SubjectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin thuốc thành công.
        /// </summary>
        internal static string Successfully_edited_medicine_information {
            get {
                return ResourceManager.GetString("Successfully edited medicine information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ nhật.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp đã tồn tại.
        /// </summary>
        internal static string Supplier_ID_already_exists {
            get {
                return ResourceManager.GetString("Supplier ID already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp đã tồn tại trong mục lưu trữ.
        /// </summary>
        internal static string Supplier_ID_already_exists_in_archive {
            get {
                return ResourceManager.GetString("Supplier ID already exists in archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp không tồn tại.
        /// </summary>
        internal static string Supplier_ID_is_not_exist {
            get {
                return ResourceManager.GetString("Supplier ID is not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ NHÀ CUNG CẤP.
        /// </summary>
        internal static string Supplier_management {
            get {
                return ResourceManager.GetString("Supplier management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục lưu trữ đang trống.
        /// </summary>
        internal static string The_archive_is_empty {
            get {
                return ResourceManager.GetString("The archive is empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm nhà cung cấp này.
        /// </summary>
        internal static string This_provider_cannot_be_added {
            get {
                return ResourceManager.GetString("This provider cannot be added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ năm.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ ba.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không khả dụng.
        /// </summary>
        internal static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác định.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không kê đơn.
        /// </summary>
        internal static string Unprescription_drug {
            get {
                return ResourceManager.GetString("Unprescription drug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thất bại.
        /// </summary>
        internal static string Update_information_failed {
            get {
                return ResourceManager.GetString("Update information failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thành công.
        /// </summary>
        internal static string Update_information_success {
            get {
                return ResourceManager.GetString("Update information success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wallet {
            get {
                object obj = ResourceManager.GetObject("wallet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tư.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        internal static string Wrong_username_or_password {
            get {
                return ResourceManager.GetString("Wrong username or password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2024.
        /// </summary>
        internal static string YearValue {
            get {
                return ResourceManager.GetString("YearValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuổi của bạn phải lớn hơn hoặc bằng {0}.
        /// </summary>
        internal static string Your_age_must_be_greater_or_equal_value {
            get {
                return ResourceManager.GetString("Your age must be greater or equal value", resourceCulture);
            }
        }
    }
}
